[build]
  publish = "Frontend"
  functions = "functions"

[[redirects]]
  from = "/api/getProducts"
  to = "/.netlify/functions/getProducts"
  status = 200

[[redirects]]
  from = "/api/searchProducts"
  to = "/.netlify/functions/searchProducts"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"